QUEUE_NAME = 'rabbitmq实现rpc1'
QUEUE_NAME_CLIENT = ''
RABBITMQ_SERVER_HOST = '10.0.0.10'
RABBITMQ_SERVER_USER = 'admin'
RABBITMQ_SERVER_PASSWORD = 'root123456'
EXCHANGE_NAME = 'rabbitmq实现rpc-exchage1'
EXCHANGE_NAME_CLIENT = ''
ROUTING_KEY = QUEUE_NAME