# Generated by Django 2.2.28 on 2022-07-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220728_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Blog'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Category'),
        ),
        migrations.AlterField(
            model_name='upanddown',
            name='is_up',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否点赞'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Blog'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='个人简介'),
        ),
    ]
